#

In [11]:
import geopandas as gpd
import pandas as pd

dbf = r'BusStops_data/PAAC_Stops_1611.dbf'

table = gpd.read_file(dbf)

pdtable = pd.DataFrame(table)
pdtable.head()

,InternalID,Name,ExternalID,Direction,Lat,Long,Time_Point,NewZone,No_Rts_Ser,Routes_161,Mode,Public_She,Public_Sto,geometry
0,S00010,10TH AVE AT ANN ST,11652.0,Inbound,40.406334,-79.908116,No,1A,1.0,53L,Bus,No Shelter,Bus Stop,POINT (-79.90811600000001 40.406334)
1,N71237,10TH AVE AT GARFIELD ST,20654.0,Outbound,40.606766,-79.753111,No,2,1.0,P10,Bus,No Shelter,Bus Stop,POINT (-79.753111 40.606766)
2,N71239,10TH AVE AT ORMOND ST,20656.0,Outbound,40.608314,-79.750500,No,2,1.0,P10,Bus,No Shelter,Bus Stop,POINT (-79.7505 40.608314)
3,N71238,10TH AVE AT SUMMIT ST,20655.0,Outbound,40.607561,-79.751760,No,2,1.0,P10,Bus,No Shelter,Bus Stop,POINT (-79.75176 40.607561)
4,S00080,12TH AVE AT AMITY ST,11650.0,Inbound,40.404325,-79.908139,No,1A,2.0,"53, 53L",Bus,No Shelter,Bus Stop,POINT (-79.90813900000001 40.404325)